export const ALL_QUESTIONS = {
  "IT / Technical": [
    { q: "What does HTML stand for?", options: ["Hyper Text Markup Language", "Home Tool Markup Language", "Hyperlinks and Text Markup Language"], correct: 0 },
    { q: "Which acts as the 'brain' of a computer?", options: ["RAM", "Motherboard", "CPU"], correct: 2 },
    { q: "Which is a frontend React framework?", options: ["Next.js", "Django", "Laravel"], correct: 0 },
    { q: "What does CSS stand for?", options: ["Creative Style Sheets", "Cascading Style Sheets", "Computer Style Sheets"], correct: 1 },
    { q: "Python files end with which extension?", options: [".pt", ".py", ".pn"], correct: 1 },
    { q: "What is the primary purpose of a 'git'?", options: ["Cloud Storage", "Version Control", "Video Editing"], correct: 1 },
    { q: "Which protocol is used for secure web browsing?", options: ["HTTP", "HTTPS", "FTP"], correct: 1 },
    { q: "What is the main function of RAM?", options: ["Permanent Storage", "Temporary Data Storage", "Graphics Rendering"], correct: 1 },
    { q: "Which of these is a NoSQL database?", options: ["MySQL", "PostgreSQL", "MongoDB"], correct: 2 },
    { q: "What does SQL stand for?", options: ["Structured Query Language", "Strong Question Language", "Simple Query Language"], correct: 0 },
    { q: "Which language is primarily used for Android apps?", options: ["Swift", "Kotlin", "C#"], correct: 1 },
    { q: "What is an API?", options: ["Application Programming Interface", "Auto Processing Index", "Advanced Program Integration"], correct: 0 },
    { q: "Which port is used by HTTP by default?", options: ["21", "80", "443"], correct: 1 },
    { q: "What is 'Docker' used for?", options: ["Web Hosting", "Containerization", "Encryption"], correct: 1 },
    { q: "What does GPU stand for?", options: ["Global Processing Unit", "Graphics Processing Unit", "General Power Unit"], correct: 1 },
    { q: "Which is a valid JavaScript data type?", options: ["Boolean", "Float", "Int64"], correct: 0 },
    { q: "What is the result of 2 + '2' in JavaScript?", options: ["4", "'22'", "NaN"], correct: 1 },
    { q: "Which company developed Java?", options: ["Microsoft", "Sun Microsystems", "Apple"], correct: 1 },
    { q: "What is a 'Kernel'?", options: ["Software application", "Core of an OS", "Hardware component"], correct: 1 },
    { q: "Which is a CSS preprocessor?", options: ["Sass", "React", "Vue"], correct: 0 },
    { q: "What does IP stand for in IP Address?", options: ["Internal Protocol", "Internet Protocol", "Instant Processor"], correct: 1 },
    { q: "Which data structure follows LIFO?", options: ["Queue", "Stack", "Linked List"], correct: 1 },
    { q: "What is the complexity of Binary Search?", options: ["O(n)", "O(log n)", "O(n^2)"], correct: 1 },
    { q: "Which tag is used for an image in HTML?", options: ["<img />", "<picture>", "<svg>"], correct: 0 },
    { q: "What does XML stand for?", options: ["Extensible Markup Language", "Extra Modern Link", "Example Markup Language"], correct: 0 },
    { q: "Which is a CSS framework?", options: ["Bootstrap", "Express", "Flask"], correct: 0 },
    { q: "What is 'Node.js'?", options: ["A browser", "A JS runtime environment", "A CSS library"], correct: 1 },
    { q: "Which operator is used for equality in JS?", options: ["=", "==", "==="], correct: 2 },
    { q: "What is 'Redux' used for?", options: ["Styling", "State Management", "API Requests"], correct: 1 },
    { q: "Which cloud provider offers AWS?", options: ["Google", "Amazon", "Microsoft"], correct: 1 },
    { q: "What is 'TypeScript'?", options: ["A new language", "A superset of JS", "A database"], correct: 1 },
    { q: "What is the default port for HTTPS?", options: ["80", "8080", "443"], correct: 2 },
    { q: "Which keyword is used to declare a constant in JS?", options: ["var", "let", "const"], correct: 2 },
    { q: "What is a 'Boolean'?", options: ["A number", "True/False value", "A string"], correct: 1 },
    { q: "Which command lists files in Linux?", options: ["ls", "dir", "cd"], correct: 0 },
    { q: "What does PHP stand for?", options: ["Hypertext Preprocessor", "Personal Home Page", "Private Host Processor"], correct: 0 },
    { q: "Which is a backend framework for Python?", options: ["Django", "Vue", "Angular"], correct: 0 },
    { q: "What is the purpose of a 'Firewall'?", options: ["Cooling", "Security", "Storage"], correct: 1 },
    { q: "Which symbol is used for ID in CSS?", options: [".", "#", "@"], correct: 1 },
    { q: "What is 'JSON' primarily used for?", options: ["Styling", "Data Interchange", "Compiling"], correct: 1 },
    { q: "Which is a type of cloud computing?", options: ["SaaS", "CSS", "SQL"], correct: 0 },
    { q: "What is 'Machine Learning'?", options: ["Robotic hardware", "Subset of AI", "Browser engine"], correct: 1 },
    { q: "Which is a mobile OS?", options: ["Windows", "Android", "macOS"], correct: 1 },
    { q: "What does SSD stand for?", options: ["Solid State Drive", "Super Speed Disk", "System Storage Device"], correct: 0 },
    { q: "Which is a web browser?", options: ["VLC", "Chrome", "Excel"], correct: 1 },
    { q: "What is '404' error?", options: ["Server Down", "Not Found", "Forbidden"], correct: 1 },
    { q: "Which tag is for a line break?", options: ["<lb>", "<br>", "<hr>"], correct: 1 },
    { q: "What does URL stand for?", options: ["Uniform Resource Locator", "Universal Radio Link", "Unique Route Locator"], correct: 0 },
    { q: "Which is a server-side language?", options: ["PHP", "HTML", "CSS"], correct: 0 },
    { q: "What is 'Responsive Design'?", options: ["Fast loading", "Mobile-friendly", "High security"], correct: 1 },
    { q: "Which is used for styling text?", options: ["<b>", "<span>", "<div>"], correct: 0 },
    { q: "What is 'Big Data'?", options: ["Large hard drive", "Large datasets", "High-res images"], correct: 1 },
    { q: "Which is an IDE?", options: ["VS Code", "Firefox", "Slack"], correct: 0 },
    { q: "What is 'Encryption'?", options: ["Data compression", "Securing data", "Deleting data"], correct: 1 },
    { q: "Which is a search engine?", options: ["Baidu", "Twitch", "Discord"], correct: 0 },
    { q: "What does BIOS stand for?", options: ["Basic Input Output System", "Binary Input Output System", "Basic Internal OS"], correct: 0 },
    { q: "Which is a loop in JS?", options: ["for", "repeat", "iterate"], correct: 0 },
    { q: "What is 'Blockchain'?", options: ["Chain of blocks", "Distributed ledger", "New internet"], correct: 1 },
    { q: "Which is a CSS property for color?", options: ["font-color", "color", "text-color"], correct: 1 },
    { q: "What is 'Open Source'?", options: ["Free software", "Public code", "No license"], correct: 1 },
    { q: "Which is a font family?", options: ["Arial", "Bold", "Italic"], correct: 0 },
    { q: "What is 'Malware'?", options: ["Hard disk error", "Malicious software", "System update"], correct: 1 },
    { q: "Which is used for version control?", options: ["SVN", "MP3", "PDF"], correct: 0 },
    { q: "What does IoT stand for?", options: ["Internet of Things", "Input Output Tool", "Internal online Time"], correct: 0 },
    { q: "Which is a JavaScript library?", options: ["jQuery", "PyQt", "Swing"], correct: 0 },
    { q: "What is 'Cloud Storage'?", options: ["Offline storage", "Remote storage", "Liquid storage"], correct: 1 },
    { q: "Which is a functional language?", options: ["Haskell", "Java", "C++"], correct: 0 },
    { q: "What is 'Virtual Reality'?", options: ["Real photos", "Simulated environment", "Video calls"], correct: 1 },
    { q: "Which is a networking device?", options: ["Router", "Monitor", "Keyboard"], correct: 0 },
    { q: "What does PDF stand for?", options: ["Portable Document Format", "Personal Data File", "Public Digital Form"], correct: 0 },
    { q: "Which is a web server?", options: ["Apache", "Android", "Apple"], correct: 0 },
    { q: "What is 'Cyberspace'?", options: ["Outer space", "Online world", "NASA server"], correct: 1 },
    { q: "Which is a unit of data?", options: ["Byte", "Watt", "Volt"], correct: 0 },
    { q: "What is 'Phishing'?", options: ["Catching fish", "Data theft scam", "System cleaning"], correct: 1 },
    { q: "Which is a backend database?", options: ["Oracle", "Outlook", "Opera"], correct: 0 },
    { q: "What does UI stand for?", options: ["User Interface", "User Input", "Universal Index"], correct: 0 },
    { q: "Which is a programming language?", options: ["Ruby", "Sapphire", "Emerald"], correct: 0 },
    { q: "What is 'Augmented Reality'?", options: ["Real + Digital", "Fake world", "3D movies"], correct: 0 },
    { q: "Which is a wireless technology?", options: ["Bluetooth", "USB", "Ethernet"], correct: 0 },
    { q: "What does FTP stand for?", options: ["File Transfer Protocol", "Fast Text Processing", "File Total Port"], correct: 0 },
    { q: "Which is an operating system?", options: ["Linux", "Safari", "Spotify"], correct: 0 },
    { q: "What is 'Deep Learning'?", options: ["Hard studying", "Advanced ML", "Sea research"], correct: 1 },
    { q: "Which is used for web styling?", options: ["CSS", "PHP", "SQL"], correct: 0 },
    { q: "What is 'VPN'?", options: ["Virtual Private Network", "Video Port Node", "Visual Power Net"], correct: 0 },
    { q: "Which is a graphic format?", options: ["PNG", "MP4", "EXE"], correct: 0 },
    { q: "What does ISP stand for?", options: ["Internet Service Provider", "Internal System Part", "Instant Signal Port"], correct: 0 },
    { q: "Which is a data structure?", options: ["Array", "Integer", "Loop"], correct: 0 },
    { q: "What is 'Bandwidth'?", options: ["Music band", "Data transfer rate", "Size of screen"], correct: 1 },
    { q: "Which is a markup language?", options: ["HTML", "C++", "Java"], correct: 0 },
    { q: "What is 'Spam'?", options: ["Useful mail", "Junk email", "Meat product"], correct: 1 },
    { q: "Which is a frontend library?", options: ["React", "Express", "Mongoose"], correct: 0 },
    { q: "What does RAM stand for?", options: ["Random Access Memory", "Read Always Memory", "Real Action Mode"], correct: 0 },
    { q: "Which is a mobile developer tool?", options: ["Flutter", "Excel", "Paint"], correct: 0 },
    { q: "What is 'Latency'?", options: ["High speed", "Delay in data", "Size of file"], correct: 1 },
    { q: "Which is a web framework?", options: ["Angular", "Python", "C"], correct: 0 },
    { q: "What is 'Cybersecurity'?", options: ["Building computers", "Protecting systems", "Using internet"], correct: 1 },
    { q: "Which is a hardware component?", options: ["Motherboard", "Windows", "Office"], correct: 0 },
    { q: "What does LAN stand for?", options: ["Local Area Network", "Long Action Node", "Light Access Net"], correct: 0 },
    { q: "Which is a video format?", options: ["AVI", "JPG", "DOCX"], correct: 0 },
    { q: "What is 'Hardware'?", options: ["Physical parts", "Software code", "Metal tools"], correct: 0 }
  ],
  "IT / Non-Technical": [
    { q: "What does SEO stand for?", options: ["Search Engine Optimization", "Secure Email Organization", "System Error Out"], correct: 0 },
    { q: "Which is used for spreadsheets?", options: ["MS Word", "MS Excel", "MS Paint"], correct: 1 },
    { q: "B2B stands for?", options: ["Back to Basics", "Business to Business", "Binary to Base"], correct: 1 },
    { q: "Which is a social media platform?", options: ["LinkedIn", "Linux", "Linode"], correct: 0 },
    { q: "What is Google Analytics used for?", options: ["Coding", "Web Traffic Analysis", "Video Editing"], correct: 1 },
    { q: "What is 'Digital Marketing'?", options: ["Selling computers", "Online advertising", "Making digital art"], correct: 1 },
    { q: "Which is a CRM tool?", options: ["Salesforce", "Photoshop", "VS Code"], correct: 0 },
    { q: "What does ROI stand for?", options: ["Return on Investment", "Rate of Interest", "Real Online Index"], correct: 0 },
    { q: "Which is used for presentations?", options: ["MS PowerPoint", "MS Access", "Notepad"], correct: 0 },
    { q: "What is 'SMM'?", options: ["Social Media Marketing", "Secure Mode Management", "System Mail Monitor"], correct: 0 },
    { q: "Which is an email client?", options: ["Outlook", "WhatsApp", "Zoom"], correct: 0 },
    { q: "What is 'E-commerce'?", options: ["Online banking", "Online shopping", "Email communication"], correct: 1 },
    { q: "Which is a cloud storage service?", options: ["Google Drive", "Netflix", "Spotify"], correct: 0 },
    { q: "What is 'Content Writing'?", options: ["Writing code", "Writing articles", "Copying files"], correct: 1 },
    { q: "Which is a video conferencing tool?", options: ["Zoom", "Excel", "SQL"], correct: 0 },
    { q: "What does KPI stand for?", options: ["Key Performance Indicator", "Keep People Informed", "Knowledge Power Index"], correct: 0 },
    { q: "Which is used for project management?", options: ["Trello", "Tally", "Twitch"], correct: 0 },
    { q: "What is 'Affiliate Marketing'?", options: ["Commission-based ads", "Buying followers", "Coding ads"], correct: 0 },
    { q: "Which is a payment gateway?", options: ["PayPal", "Facebook", "Instagram"], correct: 0 },
    { q: "What is 'Blogging'?", options: ["Online journal", "Computer error", "Game development"], correct: 0 },
    { q: "Which is a professional network?", options: ["LinkedIn", "TikTok", "Snapchat"], correct: 0 },
    { q: "What does PPC stand for?", options: ["Pay Per Click", "Personal Power Computer", "Public Private Cloud"], correct: 0 },
    { q: "Which is used for word processing?", options: ["MS Word", "MS Excel", "MS Paint"], correct: 0 },
    { q: "What is 'Target Audience'?", options: ["Group of buyers", "Group of hackers", "Software testers"], correct: 0 },
    { q: "Which is a freelance platform?", options: ["Upwork", "Windows", "Office"], correct: 0 },
    { q: "What is 'Domain Name'?", options: ["Website address", "Server owner", "Coding language"], correct: 0 },
    { q: "Which is used for data entry?", options: ["Excel", "Photoshop", "Premiere"], correct: 0 },
    { q: "What is 'Brand Awareness'?", options: ["Knowing a brand", "Buying a brand", "Naming a brand"], correct: 0 },
    { q: "Which is a search engine?", options: ["Bing", "Youtube", "Netflix"], correct: 0 },
    { q: "What does CMS stand for?", options: ["Content Management System", "Cloud Media Storage", "Computer Main System"], correct: 0 },
    { q: "Which is a digital skill?", options: ["Copywriting", "Driving", "Cooking"], correct: 0 },
    { q: "What is 'Influencer Marketing'?", options: ["Social celeb ads", "TV commercials", "Radio ads"], correct: 0 },
    { q: "Which is a web browser?", options: ["Safari", "Slack", "Skype"], correct: 0 },
    { q: "What is 'Data Mining'?", options: ["Extracting info", "Digging coal", "Deleting files"], correct: 0 },
    { q: "Which is used for database management?", options: ["MS Access", "MS Word", "MS Paint"], correct: 0 },
    { q: "What is 'User Experience (UX)'?", options: ["How users feel", "User's age", "User's location"], correct: 0 },
    { q: "Which is a collaboration tool?", options: ["Slack", "Solitaire", "Snipping Tool"], correct: 0 },
    { q: "What is 'Viral Content'?", options: ["Sick content", "Rapidly shared content", "Secret content"], correct: 1 },
    { q: "Which is an online meeting app?", options: ["MS Teams", "MS Excel", "MS Word"], correct: 0 },
    { q: "What does CTA stand for?", options: ["Call to Action", "Click to All", "Code to Access"], correct: 0 },
    { q: "Which is used for customer support?", options: ["Zendesk", "WinRAR", "VLC"], correct: 0 },
    { q: "What is 'Market Research'?", options: ["Analyzing trends", "Selling goods", "Making products"], correct: 0 },
    { q: "Which is a photo sharing app?", options: ["Instagram", "InDesign", "iTunes"], correct: 0 },
    { q: "What is 'Email Marketing'?", options: ["Sending spam", "Sending promo emails", "Deleting emails"], correct: 1 },
    { q: "Which is a business software?", options: ["ERP", "RPG", "BPM"], correct: 0 },
    { q: "What is 'Soft Skills'?", options: ["Communication", "Coding", "Designing"], correct: 0 },
    { q: "Which is a microblogging site?", options: ["Twitter / X", "Facebook", "LinkedIn"], correct: 0 },
    { q: "What is 'Lead Generation'?", options: ["Finding customers", "Leading a team", "Generating power"], correct: 0 },
    { q: "Which is a web hosting service?", options: ["Bluehost", "Bluetooth", "Blueberry"], correct: 0 },
    { q: "What is 'Crowdfunding'?", options: ["Asking public for $", "Asking bank for $", "Saving $"], correct: 0 },
    { q: "Which is a virtual assistant?", options: ["Siri", "Excel", "Chrome"], correct: 0 },
    { q: "What is 'Webinar'?", options: ["Online seminar", "Web error", "Spider web"], correct: 0 },
    { q: "Which is a graphic tool for non-designers?", options: ["Canva", "Maya", "3ds Max"], correct: 0 },
    { q: "What is 'Networking'?", options: ["Building connections", "Connecting cables", "Using WiFi"], correct: 0 },
    { q: "Which is used for online surveys?", options: ["SurveyMonkey", "SuperMario", "SnippingTool"], correct: 0 },
    { q: "What is 'Cyber Ethics'?", options: ["Online behavior", "Online gaming", "Online shopping"], correct: 0 },
    { q: "Which is a storage device?", options: ["USB Flash Drive", "Keyboard", "Mouse"], correct: 0 },
    { q: "What is 'Digital Footprint'?", options: ["Online history", "Size of screen", "Pixel size"], correct: 0 },
    { q: "Which is an e-book format?", options: ["EPUB", "EXE", "DLL"], correct: 0 },
    { q: "What is 'Remote Work'?", options: ["Working from home", "Working in office", "Working for free"], correct: 0 },
    { q: "Which is a password manager?", options: ["LastPass", "LastSeen", "LastCall"], correct: 0 },
    { q: "What is 'A/B Testing'?", options: ["Comparing 2 versions", "Testing batteries", "Grade A or B"], correct: 0 },
    { q: "Which is used for screen recording?", options: ["OBS", "Paint", "Excel"], correct: 0 },
    { q: "What is 'SaaS'?", options: ["Software as a Service", "System as a Server", "Search as a Skill"], correct: 0 },
    { q: "Which is a domain extension?", options: [".com", ".exe", ".zip"], correct: 0 },
    { q: "What is 'Hashtag'?", options: ["# symbol", "@ symbol", "& symbol"], correct: 0 },
    { q: "Which is a business model?", options: ["B2C", "P2P", "R2D2"], correct: 0 },
    { q: "What is 'Cloud Computing'?", options: ["Using internet servers", "Weather forecast", "Flying plane"], correct: 0 },
    { q: "Which is an e-wallet?", options: ["GPay", "Gmail", "GDrive"], correct: 0 },
    { q: "What is 'Freelancing'?", options: ["Self-employment", "Free work", "Holiday"], correct: 0 },
    { q: "Which is used for audio editing?", options: ["Audacity", "AutoCAD", "Access"], correct: 0 },
    { q: "What is 'Public Relations'?", options: ["Managing reputation", "Public speaking", "Dating"], correct: 0 },
    { q: "Which is a job portal?", options: ["Naukri", "Netflix", "Nintendo"], correct: 0 },
    { q: "What is 'Digital Divide'?", options: ["Tech gap", "Math problem", "Phone screen"], correct: 0 },
    { q: "Which is a browser extension?", options: ["AdBlock", "AdSense", "AdWords"], correct: 0 },
    { q: "What is 'Copywriting'?", options: ["Sales writing", "Copying text", "Legal rights"], correct: 0 },
    { q: "Which is a productivity app?", options: ["Evernote", "AngryBirds", "AmongUs"], correct: 0 },
    { q: "What is 'Artificial Intelligence'?", options: ["Machine smarts", "Human brain", "Robotic body"], correct: 0 },
    { q: "Which is an operating system?", options: ["Windows 11", "Office 365", "Adobe CC"], correct: 0 },
    { q: "What is 'Startup'?", options: ["New company", "Starting computer", "Morning routine"], correct: 0 },
    { q: "Which is a chat app?", options: ["WhatsApp", "Word", "WinZip"], correct: 0 },
    { q: "What is 'Big Data'?", options: ["Massive info", "Large screen", "Heavy computer"], correct: 0 },
    { q: "Which is a learning platform?", options: ["Coursera", "CandyCrush", "CounterStrike"], correct: 0 },
    { q: "What is 'Podcasting'?", options: ["Audio series", "Fishing", "Pod development"], correct: 0 },
    { q: "Which is used for flowcharting?", options: ["Lucidchart", "Facebook", "Flickr"], correct: 0 },
    { q: "What is 'Incognito Mode'?", options: ["Private browsing", "Fast browsing", "No internet"], correct: 0 },
    { q: "Which is a file sharing site?", options: ["WeTransfer", "Waze", "Wikipedia"], correct: 0 },
    { q: "What is 'Vlogging'?", options: ["Video blogging", "Voice logging", "Vehicle logging"], correct: 0 },
    { q: "Which is an AI assistant?", options: ["Alexa", "Alibaba", "Algorithm"], correct: 0 },
    { q: "What is 'Multitasking'?", options: ["Doing many things", "Working fast", "Doing nothing"], correct: 0 },
    { q: "Which is a video platform?", options: ["YouTube", "Spotify", "SoundCloud"], correct: 0 },
    { q: "What is 'Dark Mode'?", options: ["Dark UI", "No power", "Night time"], correct: 0 },
    { q: "Which is used for note taking?", options: ["OneNote", "OnePlus", "OneDrive"], correct: 0 },
    { q: "What is 'E-learning'?", options: ["Online learning", "Easy learning", "Early learning"], correct: 0 },
    { q: "Which is a music app?", options: ["Spotify", "Skype", "Steam"], correct: 0 },
    { q: "What is 'Subscription'?", options: ["Recurring payment", "Signing name", "Prescription"], correct: 0 },
    { q: "Which is a tech news site?", options: ["The Verge", "The Vogue", "The Voice"], correct: 0 },
    { q: "What is 'Emoji'?", options: ["Digital icon", "Mobile game", "Japanese food"], correct: 0 },
    { q: "Which is a cloud service?", options: ["Azure", "Amazon", "Acrobat"], correct: 0 },
    { q: "What is 'Information Tech'?", options: ["Managing data", "Hardware only", "Software only"], correct: 0 }
  ],
  "Designing": [
    { q: "What does CAD stand for?", options: ["Computer Art Design", "Code And Deploy", "Computer Aided Design"], correct: 2 },
    { q: "Which tool is best for UI/UX?", options: ["Figma", "AutoCAD", "Notepad"], correct: 0 },
    { q: "RGB is primarily used for?", options: ["Printing", "Digital Screens", "3D Models"], correct: 1 },
    { q: "Which is vector-based?", options: ["Photoshop", "Illustrator", "Lightroom"], correct: 1 },
    { q: "What does UI stand for?", options: ["User Interface", "Unix Index", "Unified Input"], correct: 0 },
    { q: "What does UX stand for?", options: ["User Experience", "User X-axis", "Unified X-mode"], correct: 0 },
    { q: "Which color mode is for printing?", options: ["RGB", "CMYK", "HSL"], correct: 1 },
    { q: "What is a 'Prototype'?", options: ["Final product", "Interactive model", "Coding file"], correct: 1 },
    { q: "Which is a typeface?", options: ["Helvetica", "Helsinki", "Helium"], correct: 0 },
    { q: "What is 'Typography'?", options: ["Art of text", "Map design", "Photo editing"], correct: 0 },
    { q: "Which tool is from Adobe?", options: ["InDesign", "Sketch", "Affinity"], correct: 0 },
    { q: "What is 'Wireframing'?", options: ["Skeleton layout", "Electrical work", "3D printing"], correct: 0 },
    { q: "Which is a raster format?", options: ["SVG", "JPG", "AI"], correct: 1 },
    { q: "What is 'White Space'?", options: ["Blank area", "Color white", "Clear sky"], correct: 0 },
    { q: "Which tool is for 3D modeling?", options: ["Blender", "Word", "Excel"], correct: 0 },
    { q: "What is 'Branding'?", options: ["Identity design", "Burning marks", "Buying products"], correct: 0 },
    { q: "Which is a primary color?", options: ["Red", "Orange", "Green"], correct: 0 },
    { q: "What is 'Kerning'?", options: ["Space between letters", "Line spacing", "Font size"], correct: 0 },
    { q: "Which is a web font service?", options: ["Google Fonts", "MS Fonts", "Apple Fonts"], correct: 0 },
    { q: "What is 'Logo'?", options: ["Brand symbol", "Programming language", "Game name"], correct: 0 },
    { q: "Which tool is used for photo editing?", options: ["Photoshop", "PowerPoint", "Premiere"], correct: 0 },
    { q: "What is 'Hierarchy'?", options: ["Order of importance", "A type of font", "Design software"], correct: 0 },
    { q: "Which is a neutral color?", options: ["Gray", "Red", "Blue"], correct: 0 },
    { q: "What is 'Opacity'?", options: ["Transparency", "Color depth", "Size"], correct: 0 },
    { q: "Which tool is for vector icons?", options: ["Illustrator", "Excel", "Outlook"], correct: 0 },
    { q: "What is 'Gradient'?", options: ["Color blend", "Sharp edge", "Single color"], correct: 0 },
    { q: "Which is a sans-serif font?", options: ["Arial", "Times New Roman", "Georgia"], correct: 0 },
    { q: "What is 'Alignment'?", options: ["Placing elements", "Naming files", "Choosing colors"], correct: 0 },
    { q: "Which is used for video editing?", options: ["Premiere Pro", "Photoshop", "Lightroom"], correct: 0 },
    { q: "What is 'Aspect Ratio'?", options: ["Width vs Height", "Brightness", "Resolution"], correct: 0 },
    { q: "Which tool is used for app design?", options: ["Sketch", "Access", "OneNote"], correct: 0 },
    { q: "What is 'Hue'?", options: ["Color name", "Color brightness", "Color weight"], correct: 0 },
    { q: "Which is a secondary color?", options: ["Green", "Blue", "Red"], correct: 0 },
    { q: "What is 'Saturation'?", options: ["Color intensity", "Color darkness", "Color size"], correct: 0 },
    { q: "Which tool is for layout design?", options: ["InDesign", "Paint", "Word"], correct: 0 },
    { q: "What is 'Mockup'?", options: ["Realistic design", "Funny drawing", "Coding script"], correct: 0 },
    { q: "Which is a common icon format?", options: ["SVG", "MP3", "PDF"], correct: 0 },
    { q: "What is 'Mood Board'?", options: ["Visual inspiration", "Game board", "Control panel"], correct: 0 },
    { q: "Which tool is free/open-source?", options: ["GIMP", "Photoshop", "Figma"], correct: 0 },
    { q: "What is 'Grid System'?", options: ["Alignment guide", "Electricity", "Internet"], correct: 0 },
    { q: "Which is a serif font?", options: ["Times New Roman", "Arial", "Verdana"], correct: 0 },
    { q: "What is 'Golden Ratio'?", options: ["Design proportion", "Math error", "Rich color"], correct: 0 },
    { q: "Which is used for motion graphics?", options: ["After Effects", "Acrobat", "Audition"], correct: 0 },
    { q: "What is 'Resolution'?", options: ["Image clarity", "Image size", "Image name"], correct: 0 },
    { q: "Which tool is for UX research?", options: ["Maze", "Steam", "Discord"], correct: 0 },
    { q: "What is 'User Flow'?", options: ["Path user takes", "Number of users", "User's speed"], correct: 0 },
    { q: "Which is a cool color?", options: ["Blue", "Red", "Yellow"], correct: 0 },
    { q: "What is 'Contrast'?", options: ["Difference in parts", "Same colors", "Small text"], correct: 0 },
    { q: "Which tool is for digital painting?", options: ["Procreate", "Excel", "Notepad"], correct: 0 },
    { q: "What is 'Minimalism'?", options: ["Simple design", "Complex design", "Small size"], correct: 0 },
    { q: "Which is a warm color?", options: ["Orange", "Blue", "Green"], correct: 0 },
    { q: "What is 'Accessibility'?", options: ["Inclusive design", "Fast design", "Cheap design"], correct: 0 },
    { q: "Which tool is used for font creation?", options: ["FontForge", "WordPad", "Chrome"], correct: 0 },
    { q: "What is 'Responsive Web Design'?", options: ["Adaptable layout", "Fast website", "Security"], correct: 0 },
    { q: "Which is a hex code for white?", options: ["#FFFFFF", "#000000", "#FF0000"], correct: 0 },
    { q: "What is 'Thumbnail'?", options: ["Small image", "Finger nail", "File name"], correct: 0 },
    { q: "Which tool is for collaborative design?", options: ["Figma", "Photoshop CS6", "Paint"], correct: 0 },
    { q: "What is 'Leading'?", options: ["Line spacing", "First place", "Bold text"], correct: 0 },
    { q: "Which is a display font?", options: ["Impact", "Arial", "Calibri"], correct: 0 },
    { q: "What is 'Complementary Color'?", options: ["Opposite colors", "Same colors", "Bright colors"], correct: 0 },
    { q: "Which tool is for UI components?", options: ["Storybook", "Facebook", "MacBook"], correct: 0 },
    { q: "What is 'Hero Image'?", options: ["Large banner image", "Image of a hero", "Small icon"], correct: 0 },
    { q: "Which is a mobile app tool?", options: ["Adobe XD", "VLC", "WinZip"], correct: 0 },
    { q: "What is 'Iconography'?", options: ["Symbol design", "Map drawing", "Writing"], correct: 0 },
    { q: "Which is a hex code for black?", options: ["#000000", "#FFFFFF", "#808080"], correct: 0 },
    { q: "What is 'Style Guide'?", options: ["Design rules", "Fashion book", "Travel guide"], correct: 0 },
    { q: "Which tool is for 3D animation?", options: ["Maya", "PowerPoint", "Word"], correct: 0 },
    { q: "What is 'DPI'?", options: ["Dots Per Inch", "Data Per Inch", "Digital Port In"], correct: 0 },
    { q: "Which is a design pattern?", options: ["Hamburger Menu", "Meatball Sandwich", "Pizza Slice"], correct: 0 },
    { q: "What is 'Depth'?", options: ["3D feel", "Water level", "Deep color"], correct: 0 },
    { q: "Which tool is for website building?", options: ["Webflow", "Workflow", "Workday"], correct: 0 },
    { q: "What is 'Texture'?", options: ["Surface feel", "Text size", "Text color"], correct: 0 },
    { q: "Which is a common vector file?", options: ["EPS", "BMP", "TIFF"], correct: 0 },
    { q: "What is 'Call to Action'?", options: ["Action button", "Phone call", "Movie scene"], correct: 0 },
    { q: "Which tool is for color palettes?", options: ["Coolors", "Chrome", "Calc"], correct: 0 },
    { q: "What is 'Balance'?", options: ["Equal weight", "Falling over", "Checkbook"], correct: 0 },
    { q: "Which is a font weight?", options: ["Bold", "Big", "Bright"], correct: 0 },
    { q: "What is 'Repetition'?", options: ["Repeating elements", "Deleting things", "Starting over"], correct: 0 },
    { q: "Which tool is for interaction design?", options: ["Principle", "Principal", "Principles"], correct: 0 },
    { q: "What is 'UX Audit'?", options: ["Design review", "Tax audit", "Health check"], correct: 0 },
    { q: "Which is a mobile UI framework?", options: ["Material Design", "Windows XP", "Classic Mac"], correct: 0 },
    { q: "What is 'Dark Patterns'?", options: ["Deceptive UI", "Black background", "Night design"], correct: 0 },
    { q: "Which tool is for rapid prototyping?", options: ["InVision", "Internet", "Instagram"], correct: 0 },
    { q: "What is 'Iterative Design'?", options: ["Improving in cycles", "Designing once", "Designing fast"], correct: 0 },
    { q: "Which is a UI element?", options: ["Toggle Switch", "Light Switch", "Nintendo Switch"], correct: 0 },
    { q: "What is 'Consistency'?", options: ["Uniform design", "Liquid design", "Varying design"], correct: 0 },
    { q: "Which tool is for 2D drafting?", options: ["AutoCAD", "SketchUp", "Revit"], correct: 0 },
    { q: "What is 'Bleed'?", options: ["Print margin", "Injury", "Color run"], correct: 0 },
    { q: "Which is a web standard?", options: ["W3C", "FBI", "CIA"], correct: 0 },
    { q: "What is 'Breadcrumb'?", options: ["Navigation path", "Food", "Small file"], correct: 0 },
    { q: "Which tool is for portfolio hosting?", options: ["Behance", "Binance", "Bluehost"], correct: 0 },
    { q: "What is 'Symmetry'?", options: ["Mirror image", "Chaos", "Scale"], correct: 0 },
    { q: "Which is a font style?", options: ["Italic", "Icon", "Index"], correct: 0 },
    { q: "What is 'Negative Space'?", options: ["Empty space", "Bad space", "Dark space"], correct: 0 },
    { q: "Which tool is for asset management?", options: ["Adobe Bridge", "Golden Gate", "Tower Bridge"], correct: 0 },
    { q: "What is 'Infographic'?", options: ["Visual info", "Computer info", "Photo only"], correct: 0 },
    { q: "Which is a color theory term?", options: ["Triadic", "Traffic", "Tragic"], correct: 0 },
    { q: "What is 'Design Thinking'?", options: ["Problem solving", "Thinking fast", "Daydreaming"], correct: 0 },
    { q: "Which tool is for wireframing?", options: ["Balsamiq", "Ballistic", "Basic"], correct: 0 },
    { q: "What is 'Brand Manual'?", options: ["Identity guide", "Car manual", "Book"], correct: 0 }
  ],
  "Civil": [
    { q: "Which software is standard for 2D drafting?", options: ["Maya", "AutoCAD", "Photoshop"], correct: 1 },
    { q: "Revit is primarily used for?", options: ["Video Editing", "BIM Modeling", "Web Design"], correct: 1 },
    { q: "What does RCC stand for?", options: ["Real Cement", "Reinforced Concrete Cement", "Rigid Core"], correct: 1 },
    { q: "Which tool is used for 3D elevation?", options: ["3ds Max", "Excel", "Tally"], correct: 0 },
    { q: "What is a foundation?", options: ["Roof top", "Base of structure", "Wall paint"], correct: 1 },
    { q: "What is 'BIM'?", options: ["Building Information Modeling", "Basic Iron Material", "Better Infra Mode"], correct: 0 },
    { q: "Which is a structural member?", options: ["Beam", "Door", "Window"], correct: 0 },
    { q: "What is 'Surveying'?", options: ["Measuring land", "Building walls", "Painting house"], correct: 0 },
    { q: "Which material is strongest in compression?", options: ["Concrete", "Steel", "Wood"], correct: 0 },
    { q: "What is 'Total Station'?", options: ["Surveying instrument", "Railway station", "Bus stop"], correct: 0 },
    { q: "Which is a type of bridge?", options: ["Suspension", "Subway", "Skyline"], correct: 0 },
    { q: "What is 'Levelling'?", options: ["Finding elevation", "Flat ground", "Gaming level"], correct: 0 },
    { q: "Which software is for structural analysis?", options: ["STAAD.Pro", "Word", "Paint"], correct: 0 },
    { q: "What is 'Cement'?", options: ["Binding material", "Rock", "Sand"], correct: 0 },
    { q: "Which is used for excavation?", options: ["JCB / Excavator", "Tractor", "Bike"], correct: 0 },
    { q: "What is 'Superstructure'?", options: ["Above ground part", "Below ground part", "Space station"], correct: 0 },
    { q: "Which is a non-destructive test?", options: ["Rebound Hammer", "Crushing test", "Tensile test"], correct: 0 },
    { q: "What is 'Curing'?", options: ["Keeping concrete wet", "Healing illness", "Cooking"], correct: 0 },
    { q: "Which is a type of dam?", options: ["Gravity Dam", "Space Dam", "Water Dam"], correct: 0 },
    { q: "What is 'Slump Test'?", options: ["Workability of concrete", "Strength of brick", "Hardness of steel"], correct: 0 },
    { q: "Which tool is for drafting?", options: ["Draftsman", "Drafter", "Drawer"], correct: 1 },
    { q: "What is 'Reinforcement'?", options: ["Steel bars", "Extra cement", "Stronger wood"], correct: 0 },
    { q: "Which is a building material?", options: ["Brick", "Plastic", "Paper"], correct: 0 },
    { q: "What is 'Pavement'?", options: ["Road surface", "Roof", "Wall"], correct: 0 },
    { q: "Which is used for soil testing?", options: ["Auger", "Hammer", "Screwdriver"], correct: 0 },
    { q: "What is 'Shuttering'?", options: ["Formwork", "Window cover", "Closing shop"], correct: 0 },
    { q: "Which is a type of soil?", options: ["Clay", "Metal", "Plastic"], correct: 0 },
    { q: "What is 'Plinth'?", options: ["Level above ground", "Roof", "Ceiling"], correct: 0 },
    { q: "Which software is for project planning?", options: ["MS Project", "Photoshop", "VS Code"], correct: 0 },
    { q: "What is 'Aggregate'?", options: ["Crushed stone/sand", "Glue", "Water"], correct: 0 },
    { q: "Which is a unit of length?", options: ["Meter", "Liter", "Kilogram"], correct: 0 },
    { q: "What is 'Arch'?", options: ["Curved structure", "Flat beam", "Triangle"], correct: 0 },
    { q: "Which is used for plumbing?", options: ["PVC Pipes", "Steel Bars", "Bricks"], correct: 0 },
    { q: "What is 'Lintel'?", options: ["Beam over door/window", "Roof", "Floor"], correct: 0 },
    { q: "Which is a type of cement?", options: ["OPC", "ABC", "XYZ"], correct: 0 },
    { q: "What is 'Compaction'?", options: ["Removing air from soil", "Mixing concrete", "Painting"], correct: 0 },
    { q: "Which is used for height measurement?", options: ["Altimeter", "Barometer", "Thermometer"], correct: 0 },
    { q: "What is 'Retaining Wall'?", options: ["Holds soil back", "Inside wall", "Fence"], correct: 0 },
    { q: "Which is a truss member?", options: ["Tie", "Column", "Slab"], correct: 0 },
    { q: "What is 'Admixture'?", options: ["Concrete additive", "Water only", "Sand only"], correct: 0 },
    { q: "Which is used for cutting tiles?", options: ["Tile Cutter", "Saw", "Ax"], correct: 0 },
    { q: "What is 'Floor Area Ratio (FAR)'?", options: ["Building density", "Room size", "Plot area"], correct: 0 },
    { q: "Which is a type of foundation?", options: ["Raft", "Boat", "Plane"], correct: 0 },
    { q: "What is 'Grouting'?", options: ["Filling gaps", "Digging", "Painting"], correct: 0 },
    { q: "Which tool is for measuring angles?", options: ["Theodolite", "Scale", "Tape"], correct: 0 },
    { q: "What is 'Pre-stressed Concrete'?", options: ["Tensioned steel inside", "Old concrete", "Wet concrete"], correct: 0 },
    { q: "Which is used for heavy lifting?", options: ["Crane", "Cart", "Bike"], correct: 0 },
    { q: "What is 'Slab'?", options: ["Horizontal structure", "Vertical structure", "Foundation"], correct: 0 },
    { q: "Which is a roofing material?", options: ["Asbestos", "Bricks", "Soil"], correct: 0 },
    { q: "What is 'Earthquake Resistant'?", options: ["Safe in quakes", "No quakes", "Moving house"], correct: 0 },
    { q: "Which is a unit of area?", options: ["Square Foot", "Cubic Foot", "Foot"], correct: 0 },
    { q: "What is 'Mortar'?", options: ["Cement + Sand", "Cement + Aggregate", "Sand only"], correct: 0 },
    { q: "Which is used for land clearing?", options: ["Bulldozer", "Car", "Van"], correct: 0 },
    { q: "What is 'Canal'?", options: ["Water channel", "Road", "Bridge"], correct: 0 },
    { q: "Which software is for 3D modeling?", options: ["SketchUp", "Notepad", "Calc"], correct: 0 },
    { q: "What is 'Pile'?", options: ["Deep foundation", "Heap of bricks", "Tool"], correct: 0 },
    { q: "Which is used for waterproofing?", options: ["Bitumen", "Paint", "Water"], correct: 0 },
    { q: "What is 'Culvert'?", options: ["Small bridge/pipe", "Tunnel", "Tower"], correct: 0 },
    { q: "Which is a type of staircase?", options: ["Dog-legged", "Cat-legged", "Bird-legged"], correct: 0 },
    { q: "What is 'Green Building'?", options: ["Sustainable design", "Painted green", "Garden inside"], correct: 0 },
    { q: "Which is used for road compaction?", options: ["Road Roller", "Truck", "Bus"], correct: 0 },
    { q: "What is 'Bearing Capacity'?", options: ["Soil strength", "Load on beam", "Water flow"], correct: 0 },
    { q: "Which is a drafting instrument?", options: ["T-Square", "U-Square", "V-Square"], correct: 0 },
    { q: "What is 'Estimation'?", options: ["Cost calculation", "Guessing", "Painting"], correct: 0 },
    { q: "Which software is standard for BIM?", options: ["Revit", "Word", "Excel"], correct: 0 },
    { q: "What is 'Substructure'?", options: ["Below ground", "Above ground", "Inside wall"], correct: 0 },
    { q: "Which is a structural steel shape?", options: ["I-Beam", "O-Beam", "U-Beam"], correct: 0 },
    { q: "What is 'Workability'?", options: ["Ease of placing concrete", "Working hard", "Tool quality"], correct: 0 },
    { q: "Which is used for large spans?", options: ["Truss", "Beam", "Wall"], correct: 0 },
    { q: "What is 'Expansion Joint'?", options: ["Gap for movement", "Joining pipes", "Corner joint"], correct: 0 },
    { q: "Which tool is for checking verticality?", options: ["Plumb Bob", "Scale", "Tape"], correct: 0 },
    { q: "What is 'Traffic Engineering'?", options: ["Road safety/flow", "Driving cars", "Fixing cars"], correct: 0 },
    { q: "Which is a water resource?", options: ["Reservoir", "Road", "House"], correct: 0 },
    { q: "What is 'Seismic'?", options: ["Relating to quakes", "Relating to sea", "Relating to sky"], correct: 0 },
    { q: "Which is a type of brick?", options: ["Fly Ash", "Coal Ash", "Wood Ash"], correct: 0 },
    { q: "What is 'Vibrator' used for?", options: ["Consolidating concrete", "Mixing", "Lifting"], correct: 0 },
    { q: "Which tool is for measuring distance?", options: ["Measuring Tape", "Compass", "Protractor"], correct: 0 },
    { q: "What is 'Column'?", options: ["Vertical member", "Horizontal member", "Foundation"], correct: 0 },
    { q: "Which is used for tunnel construction?", options: ["TBM", "JCB", "Crane"], correct: 0 },
    { q: "What is 'Zoning'?", options: ["Land use rules", "Finding zones", "Painting"], correct: 0 },
    { q: "Which is a unit of volume?", options: ["Cubic Meter", "Square Meter", "Meter"], correct: 0 },
    { q: "What is 'Parapet'?", options: ["Roof wall", "Floor wall", "Base wall"], correct: 0 },
    { q: "Which is used for checking levels?", options: ["Auto Level", "Auto CAD", "Auto Mobile"], correct: 0 },
    { q: "What is 'Ready Mix Concrete (RMC)'?", options: ["Pre-mixed concrete", "Dry concrete", "Old concrete"], correct: 0 },
    { q: "Which is a plumbing fitting?", options: ["Elbow", "Knee", "Hand"], correct: 0 },
    { q: "What is 'Load Bearing Wall'?", options: ["Supports roof load", "Simple partition", "Fence"], correct: 0 },
    { q: "Which is used for asphalt?", options: ["Paver", "Excavator", "Mixer"], correct: 0 },
    { q: "What is 'Cantilever'?", options: ["Beams supported at one end", "Beam at both ends", "Wall"], correct: 0 },
    { q: "Which tool is for marking?", options: ["Chalk Line", "Paint Brush", "Hammer"], correct: 0 },
    { q: "What is 'Infrastructure'?", options: ["Roads, bridges, etc.", "Inside house", "Computers"], correct: 0 },
    { q: "Which software is for civil engineering?", options: ["Civil 3D", "Photoshop", "Premiere"], correct: 0 },
    { q: "What is 'Hydrography'?", options: ["Mapping water bodies", "Drawing sky", "Mapping soil"], correct: 0 },
    { q: "Which is used for concrete mixing?", options: ["Concrete Mixer", "Blender", "Mixie"], correct: 0 },
    { q: "What is 'Sustainability'?", options: ["Eco-friendly", "Long lasting", "Cheap"], correct: 0 },
    { q: "Which tool is for tile laying?", options: ["Trowel", "Saw", "Ax"], correct: 0 },
    { q: "What is 'Sanitation'?", options: ["Waste removal", "Cleaning house", "Building walls"], correct: 0 },
    { q: "Which is a type of roof?", options: ["Gable", "Table", "Cable"], correct: 0 },
    { q: "What is 'Fire Rating'?", options: ["Fire resistance", "Fire heat", "Fire color"], correct: 0 },
    { q: "Which is a civil engineering task?", options: ["Bridge Design", "Web Design", "Logo Design"], correct: 0 },
    { q: "What is 'CAD' primarily used for?", options: ["Drafting", "Coding", "Gaming"], correct: 0 }
  ],
  "Accounting": [
    { q: "Which software is used for GST in India?", options: ["AutoCAD", "Tally Prime", "VS Code"], correct: 1 },
    { q: "What is a Ledger?", options: ["Account Book", "Hardware", "Tax Type"], correct: 0 },
    { q: "GST stands for?", options: ["Gross Sales Tax", "Goods & Service Tax", "General State Tax"], correct: 1 },
    { q: "Which is an asset?", options: ["Bank Loan", "Cash in Hand", "Creditors"], correct: 1 },
    { q: "What is SAP?", options: ["Game Engine", "ERP Software", "Design Tool"], correct: 1 },
    { q: "What is 'Double Entry'?", options: ["Every debit has credit", "Two entries for cash", "Writing twice"], correct: 0 },
    { q: "Which is a liability?", options: ["Buildings", "Accounts Payable", "Inventory"], correct: 1 },
    { q: "What is 'Trial Balance'?", options: ["Check accuracy", "End balance", "Bank statement"], correct: 0 },
    { q: "Which is a direct tax?", options: ["GST", "Income Tax", "VAT"], correct: 1 },
    { q: "What is 'Depreciation'?", options: ["Reduction in asset value", "Increase in profit", "Paying debt"], correct: 0 },
    { q: "Which is used for bookkeeping?", options: ["Journal", "Magazine", "News"], correct: 0 },
    { q: "What is 'Petty Cash'?", options: ["Small expenses", "Large cash", "Fake money"], correct: 0 },
    { q: "Which is an intangible asset?", options: ["Goodwill", "Furniture", "Vehicle"], correct: 0 },
    { q: "What is 'Audit'?", options: ["Examining accounts", "Paying taxes", "Closing business"], correct: 0 },
    { q: "Which is a financial statement?", options: ["Balance Sheet", "Checkbook", "Invoice"], correct: 0 },
    { q: "What is 'Net Profit'?", options: ["Final profit", "Total sales", "Total cost"], correct: 0 },
    { q: "Which is used for payroll?", options: ["Excel", "Photoshop", "Paint"], correct: 0 },
    { q: "What is 'Dividend'?", options: ["Share of profit", "Tax type", "Bank loan"], correct: 0 },
    { q: "Which is a current asset?", options: ["Stock", "Machinery", "Land"], correct: 0 },
    { q: "What is 'Bad Debt'?", options: ["Uncollectible money", "High interest", "Large loan"], correct: 0 },
    { q: "Which software is standard for ERP?", options: ["SAP", "Word", "Chrome"], correct: 0 },
    { q: "What is 'Balance Sheet'?", options: ["Statement of assets/libs", "List of sales", "Bank history"], correct: 0 },
    { q: "Which is an expense?", options: ["Salary", "Sales", "Capital"], correct: 0 },
    { q: "What is 'Voucher'?", options: ["Evidence of transaction", "Discount coupon", "Ticket"], correct: 0 },
    { q: "Which is used for tax filing?", options: ["IT Portal", "Facebook", "Instagram"], correct: 0 },
    { q: "What is 'Fixed Asset'?", options: ["Long term asset", "Cash", "Stock"], correct: 0 },
    { q: "Which is a nominal account?", options: ["Rent A/c", "Bank A/c", "Cash A/c"], correct: 0 },
    { q: "What is 'Bank Reconciliation'?", options: ["Matching bank & book", "Opening account", "Closing bank"], correct: 0 },
    { q: "Which is a liquid asset?", options: ["Cash", "Land", "Building"], correct: 0 },
    { q: "What is 'Equity'?", options: ["Owner's claim", "Bank debt", "Supplier debt"], correct: 0 },
    { q: "Which is a credit transaction?", options: ["Buy on credit", "Buy for cash", "Return goods"], correct: 0 },
    { q: "What is 'ROI'?", options: ["Return on Investment", "Rate of Interest", "Real Online Inc"], correct: 0 },
    { q: "Which is a financial year in India?", options: ["Apr - Mar", "Jan - Dec", "Jul - Jun"], correct: 0 },
    { q: "What is 'Debit'?", options: ["Left side entry", "Right side entry", "End balance"], correct: 0 },
    { q: "Which is a personal account?", options: ["Ram's A/c", "Purchases A/c", "Sales A/c"], correct: 0 },
    { q: "What is 'Inventory'?", options: ["Stock of goods", "List of staff", "Bank balance"], correct: 0 },
    { q: "Which is an indirect expense?", options: ["Rent", "Wages", "Raw material"], correct: 0 },
    { q: "What is 'Profit & Loss A/c'?", options: ["Shows net result", "Shows assets", "Shows cash"], correct: 0 },
    { q: "Which is used for inventory in Tally?", options: ["Stock Items", "Ledgers", "Vouchers"], correct: 0 },
    { q: "What is 'Accounting Standards'?", options: ["Rules for accounting", "Speed of work", "Design rules"], correct: 0 },
    { q: "Which is a long-term liability?", options: ["Debentures", "Creditors", "Bills Payable"], correct: 0 },
    { q: "What is 'Capital'?", options: ["Owner's investment", "City name", "Big letter"], correct: 0 },
    { q: "Which is a real account?", options: ["Furniture A/c", "Salary A/c", "Rent A/c"], correct: 0 },
    { q: "What is 'TDS'?", options: ["Tax Deducted at Source", "Total Debt System", "Tax Data Sheet"], correct: 0 },
    { q: "Which is used for data analysis?", options: ["Excel", "Paint", "Word"], correct: 0 },
    { q: "What is 'Accrual Basis'?", options: ["Record when earned", "Record when cash paid", "No record"], correct: 0 },
    { q: "Which is a current liability?", options: ["Bank Overdraft", "Long term loan", "Capital"], correct: 0 },
    { q: "What is 'Cash Flow'?", options: ["Inflow & Outflow of cash", "Total sales", "Bank profit"], correct: 0 },
    { q: "Which is a source document?", options: ["Invoice", "Ledger", "Balance Sheet"], correct: 0 },
    { q: "What is 'Drawings'?", options: ["Cash taken by owner", "Art work", "Plan"], correct: 0 },
    { q: "Which is used for GST billing?", options: ["Tally", "AutoCAD", "Figma"], correct: 0 },
    { q: "What is 'Operating Profit'?", options: ["Profit from core business", "Total profit", "Net profit"], correct: 0 },
    { q: "Which is a contra entry?", options: ["Cash to Bank", "Cash to Ram", "Bank to Rent"], correct: 0 },
    { q: "What is 'Insolvent'?", options: ["Cannot pay debts", "Very rich", "Free from debt"], correct: 0 },
    { q: "Which is an accounting software?", options: ["QuickBooks", "QuickTime", "QuickAccess"], correct: 0 },
    { q: "What is 'Gross Profit'?", options: ["Sales minus COGS", "Final profit", "Net income"], correct: 0 },
    { q: "Which is a tangible asset?", options: ["Vehicle", "Patent", "Copyright"], correct: 0 },
    { q: "What is 'Accounting Cycle'?", options: ["Steps in accounting", "Riding bike", "Time of day"], correct: 0 },
    { q: "Which is used for GST return?", options: ["GSTR-1", "GST-ABC", "GST-XYZ"], correct: 0 },
    { q: "What is 'Opening Balance'?", options: ["Balance at start", "New account", "Closing balance"], correct: 0 },
    { q: "Which is a direct expense?", options: ["Carriage Inward", "Office Rent", "Audit Fees"], correct: 0 },
    { q: "What is 'Bookkeeping'?", options: ["Recording transactions", "Storing books", "Writing stories"], correct: 0 },
    { q: "Which is an inter-state GST?", options: ["IGST", "CGST", "SGST"], correct: 0 },
    { q: "What is 'Filing'?", options: ["Submitting returns", "Cutting metal", "Naming files"], correct: 0 },
    { q: "Which is used for bank entry?", options: ["Cheque", "Stamp", "Pencil"], correct: 0 },
    { q: "What is 'Discount'?", options: ["Reduction in price", "Extra charge", "Fine"], correct: 0 },
    { q: "Which is a financial term?", options: ["Revenue", "Review", "Reveal"], correct: 0 },
    { q: "What is 'Work in Progress'?", options: ["Unfinished goods", "Full stock", "Raw material"], correct: 0 },
    { q: "Which is a type of voucher?", options: ["Payment Voucher", "Gift Voucher", "Movie Voucher"], correct: 0 },
    { q: "What is 'Accounting Equation'?", options: ["Assets = Liab + Equity", "A = B", "X + Y = Z"], correct: 0 },
    { q: "Which is used for GST calculation?", options: ["Percentage", "Addition", "Subtraction"], correct: 0 },
    { q: "What is 'Sole Proprietorship'?", options: ["Single owner business", "Group business", "No owner"], correct: 0 },
    { q: "Which is a credit note?", options: ["Issued to customer", "Issued to bank", "Issued to staff"], correct: 0 },
    { q: "What is 'Accounting Period'?", options: ["Time for reports", "Break time", "History"], correct: 0 },
    { q: "Which is used for cost accounting?", options: ["Cost Sheet", "Bed Sheet", "Balance Sheet"], correct: 0 },
    { q: "What is 'Debtor'?", options: ["Owes money to business", "Business owes money", "Bank staff"], correct: 0 },
    { q: "Which is a debit note?", options: ["Issued to supplier", "Issued to customer", "Issued to bank"], correct: 0 },
    { q: "What is 'Creditor'?", options: ["Business owes money", "Owes money to business", "Accountant"], correct: 0 },
    { q: "Which is an intangible property?", options: ["Patent", "Land", "Cash"], correct: 0 },
    { q: "What is 'Liability'?", options: ["Debt / Obligation", "Asset", "Profit"], correct: 0 },
    { q: "Which is used for daily entries?", options: ["Day Book", "Story Book", "Year Book"], correct: 0 },
    { q: "What is 'Amortization'?", options: ["Writing off intangibles", "Buying assets", "Selling assets"], correct: 0 },
    { q: "Which is a bank account?", options: ["Current Account", "Running Account", "Walking Account"], correct: 0 },
    { q: "What is 'Stock Valuation'?", options: ["Pricing inventory", "Pricing house", "Pricing staff"], correct: 0 },
    { q: "Which is used for company accounts?", options: ["Tally", "Paint", "Calculator"], correct: 0 },
    { q: "What is 'Financial Analysis'?", options: ["Interpreting data", "Recording data", "Deleting data"], correct: 0 },
    { q: "Which is an external auditor?", options: ["Chartered Accountant", "Manager", "Clerk"], correct: 0 },
    { q: "What is 'Prepaid Expense'?", options: ["Paid in advance", "Not paid", "Paid late"], correct: 0 },
    { q: "Which is used for balance sheet?", options: ["Final Accounts", "First Accounts", "No Accounts"], correct: 0 },
    { q: "What is 'Closing Stock'?", options: ["Unsold goods at end", "Total sales", "Opening stock"], correct: 0 },
    { q: "Which is a tax benefit?", options: ["Deduction", "Addition", "Fine"], correct: 0 },
    { q: "What is 'Journal Entry'?", options: ["First record", "Last record", "No record"], correct: 0 },
    { q: "Which is used for GST registration?", options: ["PAN Card", "Library Card", "Gym Card"], correct: 0 },
    { q: "What is 'Rebate'?", options: ["Tax refund/reduction", "Extra tax", "Interest"], correct: 0 },
    { q: "Which is a business entity?", options: ["Partnership", "Friendship", "Relationship"], correct: 0 },
    { q: "What is 'Accountancy'?", options: ["System of accounting", "Counting numbers", "Writing"], correct: 0 },
    { q: "Which is used for ledger posting?", options: ["Vouchers", "Journal", "Both"], correct: 2 },
    { q: "What is 'Working Capital'?", options: ["Current Assets - Liab", "Total Assets", "Bank Cash"], correct: 0 },
    { q: "Which is a financial risk?", options: ["Bad Debt", "Good Debt", "No Debt"], correct: 0 },
    { q: "What is 'Accounting'?" , options: ["Language of business", "A hobby", "A sport"], correct: 0 }
  ]
};
